MVP for showing all LSP buffer diagnostics in the quickfix
scalameta/nvim-metals pull request #28
Opened 2020-09-24 20:43 UTC by landerlo

This is a working first stab at the problem of workspace wide diagnostics in nvim-metals.
The very simple approach is to fix the quickfix with the LSP diagnostics for all the buffers.
It has the issue of updating it with newer diagnostics, to refresh we need to call the function again,
mapped as OpenAllDiagnostics.

As diagnostics are published per file, and not batched in a compilation, refreshing when we get a LspDiagnosticsRefresh event is probably too noisy and can impact when we are doing other things with the quickfix, e.g. going through grep.

We could think about only refreshing when the quickfix is open or use the quickfix change ticket to do something more clever. Also, we can could enable some filtering to only show bloop diagnostics, filter out warnings, etc. 

Nevertheless I think it's worth to start simple and this mechanism works well as it is in this PR. I needed something to refactor a big codebase and with this simple function it's a pleasure having all the errors from bloop in the quickfix-list, navigating them, using :cdo, etc.

Even thought it might not be the final solution, just as it is now improves the productivity of nvim-metals massively and makes it a viable alternative to coc. I use nvim-metals now for my commercial scala development.

2020-09-27 10:03 UTC, ckipp01 requested changes
Thanks a lot for this @landerlo! I think this is a good start. I do have a few thoughts that I'd be curios to see what you think.

1. I mentioned this in the comment, but if possible, let's try to not expose this as a command, but instead let people create a mapping for it. I'd like to have the commands aligned with the client and server commands that all editors should expose for Metals.
2. What do you think about potentially putting this in its own namespace like we do with `metals.decoration`, `metals.diagnostic`?
3. Regarding the following:
 > As diagnostics are published per file, and not batched in a compilation, refreshing when we get a LspDiagnosticsRefresh event is probably too noisy and can be too disruptive when we are doing other things with the quickfix, e.g. going through grep.

I actually think the opposite, especially seeing how [diagnostic-nvim](https://github.com/nvim-lua/diagnostic-nvim) works, I'd expect that if I'm editing a file, and I remove an error then it'd disappear from the list. I'd rather just make it impossible for someone to still select a diagnostic that is stale. Can we just hook into the `LspDiagnosticsRefresh` and remove it/replace the items in the QF list?

4. Can you also add this in to the `metals.txt` file, under a new Diagnostic API section if you agree to moving it to its own namespace?

In general, I think this is great to have. I sort of wish that this functionality could just be contained in diagnostic-nvim.

2020-09-27 17:10 UTC, landerlo commented on plugin/metals.vim
> +command! OpenAllDiagnostics lua require'metals'.open_all_diagnostics()
Sure, I'll remove the Command and add the mapping to the other examplw in nvim-lsp.vim

2020-09-27 17:19 UTC, landerlo commented
> > As diagnostics are published per file, and not batched in a compilation, refreshing when we get a LspDiagnosticsRefresh event is probably too noisy and can be too disruptive when we are doing other things with the quickfix, e.g. going through grep.
> 
> I actually think the opposite, especially seeing how [diagnostic-nvim](https://github.com/nvim-lua/diagnostic-nvim) works, I'd expect that if I'm editing a file, and I remove an error then it'd disappear from the list. I'd rather just make it impossible for someone to still select a diagnostic that is stale. Can we just hook into the `LspDiagnosticsRefresh` and remove it/replace the items in the QF list?

That's my end goal to, but I use the quickfix for other things, so I want to avoid the interference. E.g. I'm in a refactoring and doing a cdo or navigating references for a symbol or the locations from a grep search. Then I don't want the refresh to interfere with that.
The way I think about doing this is to tag the quickfix with an id, so whenever an LspDiagnosticRefresh event arrives we  check whether quickfix window is open, and if it's open,  it's a quickfix we created from metals. Only if those are true then we refresh the quickfix from the LSP diagnostics. We should do the same check when the quickfix window is open, if it's from metals we refresh. Otherwise open_all_diagnostics is the initial way to create that quickfix or to refresh and override if we have filled the qf with something else.

2020-09-27 18:16 UTC, landerlo commented
I've pushed with the feedback. Created an issue to capture the automatic refresh feature.

2020-09-28 06:53 UTC, ckipp01 approved these changes
Looks good! LGTM!

2020-09-28 06:53 UTC, merged